import type { OperationEvent, OperationSemanticKey, OperationState } from "../src/operation"

export const expectedOperationStates = [
  "proposed",
  "awaiting_approval",
  "authorized",
  "dispatch_pending",
  "dispatched",
  "effect_observed",
  "verifying",
  "reconciliation_required",
  "rolling_back",
  "completed",
  "succeeded",
  "denied",
  "cancelled",
  "failed",
  "rolled_back",
  "inconclusive",
] as const satisfies ReadonlyArray<OperationState>

export const expectedActiveOperationStates = expectedOperationStates.slice(0, 9)
export const expectedTerminalOperationStates = expectedOperationStates.slice(9)

export const expectedSemanticKeys = {
  proposed: "PLANNING",
  awaiting_approval: "AWAITING_APPROVAL",
  authorized: "READY",
  dispatch_pending: "DISPATCHING",
  dispatched: "RUNNING",
  effect_observed: "EFFECT_OBSERVED",
  verifying: "VERIFYING",
  reconciliation_required: "RECONCILIATION_REQUIRED",
  rolling_back: "RECOVERING",
  completed: "COMPLETED",
  succeeded: "VERIFIED",
  denied: "DENIED",
  cancelled: "CANCELLED",
  failed: "FAILED",
  rolled_back: "ROLLED_BACK",
  inconclusive: "INCONCLUSIVE",
} as const satisfies Readonly<Record<OperationState, OperationSemanticKey>>

export type ExpectedOperationTransition = readonly [
  from: OperationState | null,
  event: OperationEvent,
  to: OperationState,
]

// This fixture intentionally duplicates ADR-0002 independently from the implementation table.
export const expectedOperationTransitions = [
  [null, "operation.admitted", "proposed"],
  ["proposed", "policy.ask", "awaiting_approval"],
  ["proposed", "policy.allow", "authorized"],
  ["proposed", "policy.deny", "denied"],
  ["proposed", "operation.cancelled", "cancelled"],
  ["proposed", "proposal.invalidated", "cancelled"],
  ["awaiting_approval", "approval.granted", "authorized"],
  ["awaiting_approval", "approval.rejected", "denied"],
  ["awaiting_approval", "operation.cancelled", "cancelled"],
  ["awaiting_approval", "approval.invalidated", "cancelled"],
  ["authorized", "dispatch.requested", "dispatch_pending"],
  ["authorized", "operation.cancelled", "cancelled"],
  ["authorized", "authorization.invalidated", "cancelled"],
  ["dispatch_pending", "executor.accepted", "dispatched"],
  ["dispatch_pending", "dispatch.proved_unclaimed", "authorized"],
  ["dispatch_pending", "dispatch.cancelled_unclaimed", "cancelled"],
  ["dispatch_pending", "authorization.invalidated_unclaimed", "cancelled"],
  ["dispatch_pending", "dispatch.claim_unknown", "reconciliation_required"],
  ["dispatched", "effect.completed", "completed"],
  ["dispatched", "effect.observed", "effect_observed"],
  ["dispatched", "execution.failed_without_effect", "failed"],
  ["dispatched", "cancellation.completed_without_effect", "cancelled"],
  ["dispatched", "effect.unknown", "reconciliation_required"],
  ["effect_observed", "verification.started", "verifying"],
  ["effect_observed", "verification.unavailable_or_stale", "reconciliation_required"],
  ["effect_observed", "verification.snapshot_invalidated", "reconciliation_required"],
  ["effect_observed", "recovery.operation_linked", "rolling_back"],
  ["verifying", "verification.passed", "succeeded"],
  ["verifying", "verification.failed", "failed"],
  ["verifying", "verification.failed_with_recovery_link", "rolling_back"],
  ["verifying", "verification.unknown", "reconciliation_required"],
  ["verifying", "verification.evidence_invalidated", "reconciliation_required"],
  ["reconciliation_required", "probe.confirmed_effect", "effect_observed"],
  ["reconciliation_required", "probe.proved_no_effect_and_retry_authorized", "authorized"],
  ["reconciliation_required", "probe.proved_no_effect", "failed"],
  ["reconciliation_required", "probe.proved_no_effect_after_cancel", "cancelled"],
  ["reconciliation_required", "recovery.operation_linked", "rolling_back"],
  ["reconciliation_required", "ambiguity.closed", "inconclusive"],
  ["rolling_back", "recovery.verified", "rolled_back"],
  ["rolling_back", "recovery.failed_known_state", "failed"],
  ["rolling_back", "recovery.unknown", "reconciliation_required"],
  ["proposed", "policy.invalidated", "proposed"],
  ["dispatched", "cancellation.requested", "dispatched"],
  ["dispatched", "authorization.revoked_after_acceptance", "dispatched"],
  ["dispatched", "execution.timeout_observed", "dispatched"],
  ["dispatched", "lease.lost", "dispatched"],
  ["reconciliation_required", "reconciliation.probe_recorded", "reconciliation_required"],
  ["reconciliation_required", "lease.renewed", "reconciliation_required"],
  ["reconciliation_required", "reconciliation.owner_note_recorded", "reconciliation_required"],
  ["reconciliation_required", "reconciliation.deadline_changed", "reconciliation_required"],
  ["rolling_back", "recovery.progress_recorded", "rolling_back"],
] as const satisfies ReadonlyArray<ExpectedOperationTransition>
